include: Fix conflicting types for 'size_t' with musl build
We are trying to build LK with musl library, and musl
already defines size_t data type with __DEFINED_size_t,
so we get the error saying that:
- error: conflicting types for 'size_t'

Hence we will not define size_t if __DEFINED_size_t
is defined.

Change-Id: Ifdd17e7f19899e2fc3c736471eefc0794f91875a
Signed-off-by: Ram Chandra Jangir <rjangir@codeaurora.org>